### ISSUE TITLE
[PROPOSAL && QUESTION] 수정요청 및 추가 기능에 대한 의견

### ISSUE THREAD

**Issue by kimscastle** [Genti2024/GenTI-BE#10]
버그, 기능 추가 외의 자유롭게 의견 작성해주시면 답변 드립니다.

## 1

만들어주신 API에서 사진생성 요청의 경우에
<img width="1397" alt="스크린샷 2024-06-10 오전 8 09 09" src="https://github.com/Genti2024/GenTI-BE/assets/99013115/5e47af7b-1b3f-4e1c-a7ea-e9a51a938d4d">

200으로 실제 데이터가 들어오면 아래와같은 형식으로 오는데 swagger에 있는 응답값이랑 많이 다른거같아서 문의드립니다
```swift
{
  "success" : true,
  "errorCode" : null,
  "response" : true,
  "errorMessage" : null
}
```

우선 response는 {}가 아닌 bool이되어야할거같아용
그리고 저번에 swagger에서 nullable관련해서 말씀해주셨는데
errorcode랑 message가 nullable처리가 안되어있는거같아요
<img width="1320" alt="스크린샷 2024-06-10 오전 8 11 32" src="https://github.com/Genti2024/GenTI-BE/assets/99013115/1bce7363-7e01-4647-aa4c-50ea1d310356">

이슈까지는 아닌거같은데 nullable적용과 실제 response와 swagger의 타입을 맞춰주시면 감사하겠습니다~

## 2

저희가 fcm을 통해서 이제 push notification(푸시알림이라고 하겠습니당)을 보내게될텐데
사실 유저가 앱을 사용하고있지않을때(앱이 background상태에있을때)는 푸시알림이와서 그 푸시알림을 터치하면 앱이 켜지고 켜지자마자 사진생성이 완료되었다고 보여주면 되는데

문제는 앱을 사용하고있을때입니다. 제가 생각했을때는 두가지 일것같습니다

1. 앱을사용하고있을때도 사진생성이 완료되었다는 푸시알림을 보낸다
2. 앱을사용하고있을때는 사진생성이 완료되었다는 푸시알림을 보내지 않는대신 socket통신을 통해서 실시간 업데이트 상황을 받는다

혹시 어떻게 생각하시는지 궁급합니다

편한 방법은 1번일거같긴한데 보통 앱을 사용하고있으면 푸시알림이 안오지않나싶어서 2번방법을 생각해봤습니다!

## 3
그리고 사진생성에서 비율, 프레임, 앵글선택하는 쪽 enum을 swagger에서 확인했는데

<img width="523" alt="스크린샷 2024-06-10 오전 8 20 18" src="https://github.com/Genti2024/GenTI-BE/assets/99013115/266f419b-1051-4392-9717-a02602dfd7e4">

카메라 프레임이 5개로 설정되어있더라고요
<img width="767" alt="스크린샷 2024-06-10 오전 8 20 42" src="https://github.com/Genti2024/GenTI-BE/assets/99013115/bb6c7861-8b96-4557-a957-011edd2bfa01">

변경된 디자인 보시면 총 4개라 이부분 수정해주시면 좋을거같습니다~
자유 포함해서 4개가 뭔지 우기한테 물어보고 디스코드메세지 보내겠습니다!

**Comment by BYEONGRYEOL** [comment]
1. 확인했습니다. Swagger 문서화된 부분을 다듬어야할 것 같습니다!

**Comment by BYEONGRYEOL** [comment]
2. 저도 비즈니스  로직상 2번 안이 더 합리적이라고생각합니다. 2번을 가능한 적용하려고 하되, 학습에 어려움을 겪거나 하는 문제가 있으면 어쩔 수 없이 1번으로 가는 방향으로 가면 될 것 같습니다! 급한거 쳐내고 2번 안을 백단에서 어떻게 구현하는지 학습해보겠습니다!

**Comment by BYEONGRYEOL** [comment]
3.  우기한테 물어봤습니다!
