### ISSUE TITLE
[FEATURE REQUEST] 예시사진 API 호출 시 랜덤으로 순서를 섞어주는 기능을 추가

### ISSUE THREAD

**Issue by LeeJae-H** [Genti2024/GenTI-BE#108]
**feature describe**
"/api/v1/users/examples/with-picture" api 호출 시 랜덤으로 순서를 섞어주는 기능 추가

**screenshots**

**Comment by LeeJae-H** [comment]
+추가
- 랜덤으로 순서를 섞는 것 + 맨 앞의 데이터는 RATIO_3_2인 데이터가 와야함

**Comment by BYEONGRYEOL** [comment]
GARO SERO~~
