### ISSUE TITLE
[FEATURE REQUEST] 유저의 사진 전체 조회 api 페이지네이션 없는 버전 추가

### ISSUE THREAD

**Issue by LeeJae-H** [Genti2024/GenTI-BE#111]
**feature describe**
"/api/v1/users/pictures/my" 엔드포인트를 가진 api가 이미 존재하지만,
페이지네이션 없는 버전도 추가하기로 함

**screenshots**

**Comment by BYEONGRYEOL** [comment]
완료된것으로 처리하겠습니다
