### ISSUE TITLE
[FEATURE REQUEST] 회원가입API response 수정

### ISSUE THREAD

**Issue by LeeJae-H** [Genti2024/GenTI-BE#118]
**feature describe**
유저데이터 기록을 프론트에서 하게 되어 유저 정보를 프론트 쪽에서 알아야하는 상황인데, 이를 회원가입 완료 시점에 주는 것이 좋아 보임.

따라서 회원가입 api ("/api/v1/users/signup")의 response를 기존의 Boolean 값 대신,
1. 이메일
2. 소셜로그인타입
3. 닉네임
4. 태어난년도
5. 성별
(+ 이후 추가될 수도 있긴함) 
로 수정해야 함.

**screenshots**

**Comment by BYEONGRYEOL** [comment]
고생하셨습니당
