### ISSUE TITLE
[BUG] 한 개의 사진 생성 요청이 여러번 전송되는 문제

### ISSUE THREAD

**Issue by LeeJae-H** [Genti2024/GenTI-BE#138]
**Describe the bug**
(인터넷 연결이 좋지 않은 상황에서) 사진 생성 버튼을 연타했더니 주문이 여러개 들어와졌습니다.

**To Reproduce**
1. 
POST
"/api/v1/users/picture-generate-requests"
2. 
request body : PGREQSaveRequestDto
jwt(user)

**Expected behavior**
기존 로직 수행에 앞서, 
해당 유저의 가장 최근 사진 생성 요청이 존재할 때, 이 요청의 status값이 AWAIT_USER_VERIFICATION이면 "이미 처리된 사진 생성 요청입니다" 예외 전달
---(위에 것으로 해결되지 않음)---

**Screenshots**

**Additional context**

**Comment by BYEONGRYEOL** [comment]
1. 이미 진행중인 요청이 있는지 검사하는 로직 - PictureGenerateRequestStatus 로 검증 가능
2. 해당 유저에 대해서 redis를 이용하여 lock을 거는 로직 - LOCK : {userId} : {메서드명}(createPGREQ) 의 패턴으로 key 생성

추가하겠습니다.
