### ISSUE TITLE
[DEV]API 엔드포인트 수정

### ISSUE THREAD

**Issue by LeeJae-H** [Genti2024/GenTI-BE#27]
**Description**
"/api/users/v1" (전) => "/api/v1/users" (후) 
위와 같이 v1이 포함된 모든 API의 엔드포인트를 "/api/v1/..."의 형태로 통일시켜야 함.
또한, 이에 따른 SecurityConfig 파일도 함께 수정.

**Additional Info**

**Feature Info**

**Comment by LeeJae-H** [comment]
25e3159f06a1e12118567c909580ffc8d8d097e9

**Comment by BYEONGRYEOL** [comment]
api 엔드포인트는 모두 수정된 것으로 판단됩니다. 이슈 닫을게요

**Comment by BYEONGRYEOL** [comment]
아 마지막에 "/" 있던거 확인했나요 마르? 요거
/api/mar 하고, /api/mar/ 하고 다른 url로 인식되어서 프론트딴에서 문의온거 제가 쳤습니다 팔로업해주세용 @LeeJae-H  확인하시고 이슈 닫아주세요~~~

**Comment by LeeJae-H** [comment]
수정하신 거 확인했습니다.

혹시 수정하신 부분에서,
@GetMapping("")
대신
@GetMapping
이거는 어떠신가요?
후자가 괜찮으시다면 제가 수정해놓겠습니다. 아니면 그냥 납두겠습니다 ㅎㅎ..

+ 답변확인하고 이슈 닫겠습니다.

**Comment by BYEONGRYEOL** [comment]
좋은데요? 다음 마르 pr에 포함하시져
