### ISSUE TITLE
[DEV] Oauth2 적용으로 인한 User Entity 변경

### ISSUE THREAD

**Issue by BYEONGRYEOL** [Genti2024/GenTI-BE#29]
**Description**

1. 기존 User Entity에는 image_url(not null) 이라는 필드명으로 Oauth profile image url을 저장하는 부분이 있었는데, 현재 젠티 정책상 Oauth Provider에게 profile image url을 받을 지 말지 모호한 상황에서 not null 조건을 유지하기 어렵다고 판단하였습니다.
2. image_url이라는 변수 명이 젠티 도메인 내에서 사용되는 사진인지 oauth사진인지 모호하여 변수명을 oauthImageUrl(컬럼명 oauth_image_url) 로 변경 하려고 합니다.
3. 1,2에 따라서, local,dev 환경에서 users 테이블의 image_url 컬럼을 삭제하고 hibernate update 옵션에 의존하여 oauth_image_url 컬럼 생성하겠습니다.

4. 멀티모듈 리팩터링 전 버전의 db를 export & import하여(07/08) users 테이블에 boolean 'login' 컬럼이 남아있는 상황입니다. 해당 컬럼 제거하려고합니다.

5. birthDate 필드(birth_date 컬럼, date형식) 또한 oauth provider가 String 형식으로 생일을 제공하는 이유로 형식을 String(varchar(10)){형식 yyyy-mm-dd} 로 변경하고자합니다. 

@LeeJae-H 마르 로컬 db에 반영해야합니다
**Additional Info**

**Feature Info**

**Comment by BYEONGRYEOL** [comment]
서버에는 적용했구요, 마르가 확인하면 닫겠습니다

**Comment by LeeJae-H** [comment]
1,2,3 
=> image_url 컬럼명을 oauth_image_url으로 변경(새로 컬럼 생성) + not null 조건 유지 어려움
4 
=> login 컬럼 제거
5 
=> birth_date 컬럼의 타입을 date에서 String으로 변경

+ 해당 내용들 마르의 로컬 DB에 반영 

확인했습니다!

**Comment by BYEONGRYEOL** [comment]
킹 갓 마르
