### ISSUE TITLE
[FEATURE REQUEST] 생성완료 여부 API 수정

### ISSUE THREAD

**Issue by BYEONGRYEOL** [Genti2024/GenTI-BE#31]
**feature describe**

사용자가 자신의 사진생성요청이 어느단계인지에 따라 FE에서 분기처리해야한다.

1. 작업중인 사진생성요청 없음 -> 사진생성요청 화면으로 이동
2. 작업이 진행중 -> 진행중입니다 화면으로 이동
3. 작업이 완료됨
3-1. 사용자가 완료된 사진을 확인한 적이 없음 -> 사진 생성 완료 화면(아래 스샷 참고)으로 이동
3-2. 사용자가 완료된 사진을 이미 확인함 -> 1번과 같이 처리

이에 따라 아래와 같이 응답

``` json
{
    "FE에게 보여질 사진생성요청작업상태 3가지" : "상태",
    "완료된 사진응답객체" : "완료사진응답 객체" (위의 상태가 1,2, 3-2번인 경우에는 null)
}
```
* 완료사진응답 객체에는 완료사진의 정보(id, url)와 완료 응답 자체의 id값도 들고있어 유저가 신고할때 활용할 수 있습니다.
** 구체적인 응답형식은 변경될 수 있음

**screenshots**
A... 사진생성완료화면 
![image](https://github.com/user-attachments/assets/007e0e45-9941-4173-b0c4-78f0a93858ae)

https://www.notion.so/API-89f620d06f394d8d9a2f62746ebc89c3?pvs=4

**Comment by BYEONGRYEOL** [comment]
@Marchbreeze  저는 위의 상황기준으로 API 수정작업 들어가려고합니다. 제가 맞게 이해했는지 확인해주실래용?

**Comment by Marchbreeze** [comment]
@BYEONGRYEOL 네 제가 이해하기로는 저 방식으로 수정하는 게 좋을 것 같습니다!
다만 이 의견이 @kimscastle 유스 의견이었어서, 혹시 더블 체크 가능하실까요?

**Comment by kimscastle** [comment]
네 좋습니다! 진행해주십쇼!
완료되면 칸반보드에서 done으로 수정해주시고
디스코드 요청사항-notification 채널에


@Youth @March
Lottie파일 json형식으로 변환(splash) - 작업완료

해당형식으로 글올려주세용~

**Comment by BYEONGRYEOL** [comment]
유저가 사진생성'요청'의 상태를 조회한 후
만약 생성완료되었으나 확인하지 않은 사진을 확인할 때는 사진생성'응답'의 확인여부를 변경하는 것이 되므로, 

사진생성요청 상태 조회는 PGREQ Controller,
완료된 사진 확인처리는 PGRES Controller에서 담당,

(백엔드 기록용입니다.)
