### ISSUE TITLE
[FEATURE REQUEST] FE<->BE 최초가입자 / 기가입자 구분 로직 수정

### ISSUE THREAD

**Issue by BYEONGRYEOL** [Genti2024/GenTI-BE#74]
**feature describe**

기존 로직은 다음과 같습니다.

- KakaoJwtResponse (accessToken, refreshToken, UserRole)
    - 신규 사용자 : (`null`, `null`, OAUTH_FIRST_JOIN)
    - 기존 사용자 : (accessToken, refreshToken, `null`)

다음과 같은 이유로 변경하고자합니다.
1. token response에 null이 들어가는거 자체의 문제
2. 신규사용자의 경우 FE단에서 해당 응답을 받은 뒤 최종가입처리를위해 생년,성별 데이터를 입력받고 서버에 쏠 때, 방금 최초가입한 유저라는 사실을 알리기 힘들다(token response를 못받았으니까)
3. 추후 공급자가 앱을 이용해서 작업하게될 수도 있음을 고려하여 기존 사용자라도 null보단 실제 해당 사용자의 ROLE을 주는 것이 마땅해보임(공급자 고려하지않더라도 null보단 값이 있는게 낫다고 생각합니다 저는)

변경된 로직 

- KakaoJwtResponse (accessToken, refreshToken, UserRole)
    - 신규 사용자 : (accessToken, refreshToken, OAUTH_FIRST_JOIN)
    - 기존 사용자 : (accessToken, refreshToken, {USER, _CREATOR_})

위 기능 이후에 사용자에게 생년,성별을 받아 최종가입처리하는 핸들러는 AUTH CONTROLLER 에 만들지 USER CONTROLLER 에 만들지 같이 얘기해보시죠 

**screenshots**

어디서 쓰는 기능인지 알아볼 수 있는 화면 있으면 도움이 됩니다.

**Comment by LeeJae-H** [comment]
변경 이유에 동의합니다.

**Comment by LeeJae-H** [comment]
"위 기능 이후에 사용자에게 생년,성별을 받아 최종가입처리하는 핸들러는 AUTH CONTROLLER 에 만들지 USER CONTROLLER 에 만들지 같이 얘기해보시죠"

=> 제 의견은 AUTH인데, 이유는 
- 해당 API의 목적이 '사용자 정보 업데이트'가 아니라 '회원가입'이고, 회원가입은 인증과 관련된다고 생각해서
입니다.
